typography_spectrum: 0.027065221220254898
color:
  brandStrength: 0.03748326515778899
  lightness: 0.6922704905737191
  saturation: 0.4714916651137173
  rhythmicContrast: 0.9987129317596555
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.9336585125420243
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/50a00739-fe85-480c-815d-5b3d2698663a.png
name: Gentle Family Dentistry
navigation:
  - name: Home
    id: b6424f9d-7c8d-4303-a558-3a24a019e2e9
    type: content
  - name: Meet the Doctors
    id: 457982d5-7216-4bbb-a48d-8a30c36b1aea
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4401811d-3d83-4cd9-a9ab-61fae3d5fdc3.png
title: Gentle Family Dentistry
description: Gentle dentistry for your family and friends.
